@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package io.bluebeaker.questtweaker.utils;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;