@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.bluebeaker.questtweaker.ctintegration.questobjects;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;